### ISSUE TITLE
Filter out results with _deleted metatag

### ISSUE THREAD

**Issue by olorin** [anchor/sieste#20]
We have a crapton of metrics no-one cares about anymore except in very specific cases (i.e., we don't need to return results for metrics for servers which were decommed years ago). We don't want to throw these away as they're still useful for things like training datasets, but we also don't want them polluting our search results. Therefore, we will tag these with _deleted (or something else; if anyone objects to '_deleted' please say so).

Default to filtering out results with this tag, and add a query option to disable the filtering-out.

(Alternatively, is anchor/chevalier a better place for this kind of functionality?)

**Comment by glasnt** [comment]
Given not all searching occurs through sieste, but via chevalier/chevalier-common, it makes sense to put this in chevalier itself.
Exposing an ability to optionally retrieve deleted results would be a param sieste would pass down to chevalier. 
We would also possibly want to update the empty-source-dict-is-deleted functionality from whereever it still lives in the stack

**Comment by olorin** [comment]
I don't think the empty-source-dict-is-deleted convention needs to change; there's not much point in including empty sourcedicts in a sourcedict search engine, in any case.

**Comment by olorin** [comment]
Moved to anchor/chevalier#26.
